---
title: "R Notebook"
output: html_notebook
---

```{r}
library(recipes)
library(rsample)
library(modeldata)
set.seed(12345)
data("clients")
```

```{r}
rec <- recipe(Exited ~ ., data = client_train)
rec
```

```{r}
prop.table(table(clients$Exited))
```


```{r}
library(ggplot2)



ggplot(clients, aes(x = CreditScore, fill = factor(Exited))) +
  geom_histogram(position = "identity", color = "black", linewidth = 0.3) +
  scale_fill_manual(values = c("0" = "steelblue", "1" = "darkgray"),
                    labels = c("0", "1"),
                    name = "Exited") +
  labs(title = "Distribución de CreditScore por Exited",
       x = "CreditScore",
       y = "Frecuencia") +
  theme_minimal() 




```

```{r}
ggplot(clients, aes(x = Geography, fill = factor(Exited))) +
  geom_bar(position = "dodge") +
  scale_fill_manual(values = c("steelblue", "orange"), name = "Exited") +
  labs(title = "Frecuencia por País y Exited",
       x = "País",
       y = "Frecuencia") +
  theme_minimal()
```
```{r}
tabla_frecuencias <- table(clients$Geography, clients$Exited)

tasas_abandono <- prop.table(tabla_frecuencias, margin = 1)
round(tasas_abandono * 100, 2)


```


```{r}
clients$CustomerId <- factor(clients$CustomerId)
clients$Exited <-factor(clients$Exited)
clients$HasCrCard <- factor(clients$HasCrCard)
clients$IsActiveMember <- factor(clients$IsActiveMember)
summary(clients)
```

```{r}


par(mfrow = c(2, 3), mar = c(1, 3, 2, 1), oma = c(0, 0, 3, 0))

boxplot(clients$CreditScore, main = "CreditScore" )
boxplot(clients$Age, main = "Age")
boxplot(clients$Tenure, main = "Tenure")
boxplot(clients$Balance, main = "Balance")
boxplot(clients$NumOfProducts, main = "NumOfProducts")
boxplot(clients$EstimatedSalary, main = "EstimatedSalary")

mtext("Distribución y Dispersión de Variables Numéricas", outer = TRUE, cex = 1.2, font = 2)

par(mfrow = c(1, 1))



```

```{r}
library(ggplot2)
library(reshape2)

num <- clients[sapply(clients, is.numeric)]
num$Exited <- clients$Exited

datos <- melt(num, id.vars = "Exited")

ggplot(datos, aes(x = factor(Exited), y = value, fill = factor(Exited))) +
  geom_boxplot() +
  facet_wrap(~variable, scales = "free") +
  theme_minimal()
```


```{r}
library(corrplot)

num_vars_df <- clients[, sapply(clients, is.numeric)]

cor_matrix <- cor(num_vars_df, use = "complete.obs")
corrplot(cor_matrix, method = "color", type = "upper", 
addCoef.col = "black", tl.col = "black", tl.srt = 45, 
diag = FALSE, number.cex = 0.7)

```


```{r}
library(ggplot2)
library(patchwork)

p1 <- ggplot(clients, aes(x = Gender, fill = factor(Exited))) +
  geom_bar(position = "fill") +
  theme_minimal() +
  labs(y = "Proporción", x = "Gender", fill = "Exited")

p2 <- ggplot(clients, aes(x = factor(HasCrCard), fill = factor(Exited))) +
  geom_bar(position = "fill") +
  theme_minimal() +
  labs(y = "", x = "HasCrCard", fill = "Exited") 

p3 <- ggplot(clients, aes(x = factor(IsActiveMember), fill = factor(Exited))) +
  geom_bar(position = "fill") +
  theme_minimal() +
  labs(y = "", x = "IsActiveMember", fill = "Exited")

final_plot <- (p1 | p2 | p3) + 
  plot_layout(guides = "collect") & 
  theme(legend.position = "bottom")

final_plot
```

```{r}
clients <- clients %>%
  mutate(Gender_Active = paste(Gender, ifelse(IsActiveMember == 1, "Activo", "Inactivo"), sep = "_"))

 ggplot(clients, aes(x = factor(Gender_Active), fill = factor(Exited))) +
  geom_bar(position = "fill") +
  theme_minimal() +
  labs(y = "", x = "Active", fill = "Exited")
```
```{r}
prop.table(table(clients$Gender_Active))
```


```{r}
ggplot(clients, aes(x = factor(NumOfProducts), fill = factor(Exited))) +
  geom_bar(position = "fill") +
  theme_minimal() +
  labs(title = "Proporción de Fuga por Número de Productos",
       x = "NumOfProducts", y = "Proporción", fill = "Exited")
```
```{r}
prop.table(table(clients$NumOfProducts))
```


